services:
  web:
    build:
      dockerfile: Dockerfile
    ports: 
      - 80:80
    links:
      - "db:database"
    volumes:
      - .\elektronicznaPrzychodnia:/var/www/html
  db:
    build:
      dockerfile: DbDockerfile
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: clinic
      MYSQL_USER: admin
      MYSQL_PASSWORD: P@ssw0rd
      MYSQL_TCP_PORT: 3306
    ports:
      - 3306:3306
    volumes:
      - .\elektronicznaPrzychodnia:/home/project